# Server endpoint (string)
server_url: "https://meneame-diario.appspot.com"
# Men√©ame endpoint (string)
meneame_url: "https://meneame.net"
# Refresh rate for the digest, in days (uint)
refresh_rate: 1
# Maximum stories per digest (uint)
max_stories: 10
